# Login
post http://localhost:3000/api/users/login
Content-Type: application/json

{
    "email": "bernadett1104@gmail.com",
    "password": "admin"
}

### User add
post http://localhost:3000/api/users/registration
Content-Type: application/json

{
    "firstname": "Mark",
    "lastname": "Sándor",
    "email": "bernadett1104@gmail.com",
    "password": "admin",
    "gender": "nő",
    "permission": 1
}

### Users
get http://localhost:3000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOnsiaWQiOjMsIm5hbWUiOiJOYWd5IFPDoW5kb3IiLCJlbWFpbCI6InNhbmRvckBnbWFpbC5jb20iLCJwZXJtaXNzaW9uIjoxfSwiaWF0IjoxNjQ4NzI0NTcxLCJleHAiOjE2NDg3MjgxNzF9.twd3PxUOjyi8eIoLN_d8hM0BrS_Xmst7pZIBxSflEeQ

### One User
get http://localhost:3000/api/users/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOnsiaWQiOjMsIm5hbWUiOiJOYWd5IFPDoW5kb3IiLCJlbWFpbCI6InNhbmRvckBnbWFpbC5jb20iLCJwZXJtaXNzaW9uIjoxfSwiaWF0IjoxNjQ4NzI0NTcxLCJleHAiOjE2NDg3MjgxNzF9.twd3PxUOjyi8eIoLN_d8hM0BrS_Xmst7pZIBxSflEeQ

### User edit
put http://localhost:3000/api/users
Content-Type: application/json

{
    "firstname": "Bernadett",
    "lastname": "Sándor",
    "email": "bernadett1104@gmail.com",
    "password": "admin",
    "gender": "férfi",
    "permission": 1,
    "id": 7
}

### Delete user
delete http://localhost:3000/api/users
Content-Type: application/json

{
    "id": 8
}





# Categories

### Category add
post http://localhost:3000/api/categories/newcategory
Content-Type: application/json

{
    "name": "multiplayer"
}

### Categories
get http://localhost:3000/api/categories/allcategories
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOnsiaWQiOjMsIm5hbWUiOiJOYWd5IFPDoW5kb3IiLCJlbWFpbCI6InNhbmRvckBnbWFpbC5jb20iLCJwZXJtaXNzaW9uIjoxfSwiaWF0IjoxNjQ4NzI0NTcxLCJleHAiOjE2NDg3MjgxNzF9.twd3PxUOjyi8eIoLN_d8hM0BrS_Xmst7pZIBxSflEeQ

### One category
get http://localhost:3000/api/categories/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOnsiaWQiOjMsIm5hbWUiOiJOYWd5IFPDoW5kb3IiLCJlbWFpbCI6InNhbmRvckBnbWFpbC5jb20iLCJwZXJtaXNzaW9uIjoxfSwiaWF0IjoxNjQ4NzI0NTcxLCJleHAiOjE2NDg3MjgxNzF9.twd3PxUOjyi8eIoLN_d8hM0BrS_Xmst7pZIBxSflEeQ

### Category edit
put http://localhost:3000/api/categories/categoryupdate
Content-Type: application/json

{
    "name": "multiplayer_updated",
    "id": 5
}

### Delete category
delete http://localhost:3000/api/categories/categorydelete
Content-Type: application/json

{
    "id": 1
}





# Developers

### Developer add
post http://localhost:3000/api/developers
Content-Type: application/json

{
    "developer": "Riot Games"
}

### Developers
get http://localhost:3000/api/developers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOnsiaWQiOjMsIm5hbWUiOiJOYWd5IFPDoW5kb3IiLCJlbWFpbCI6InNhbmRvckBnbWFpbC5jb20iLCJwZXJtaXNzaW9uIjoxfSwiaWF0IjoxNjQ4NzI0NTcxLCJleHAiOjE2NDg3MjgxNzF9.twd3PxUOjyi8eIoLN_d8hM0BrS_Xmst7pZIBxSflEeQ

### One ceveloper
get http://localhost:3000/api/developers/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOnsiaWQiOjMsIm5hbWUiOiJOYWd5IFPDoW5kb3IiLCJlbWFpbCI6InNhbmRvckBnbWFpbC5jb20iLCJwZXJtaXNzaW9uIjoxfSwiaWF0IjoxNjQ4NzI0NTcxLCJleHAiOjE2NDg3MjgxNzF9.twd3PxUOjyi8eIoLN_d8hM0BrS_Xmst7pZIBxSflEeQ

### Decelopers edit
put http://localhost:3000/api/developers
Content-Type: application/json

{
    "developers": "Riot Games_updated",
    "id": 1
}

### Delete developer
delete http://localhost:3000/api/developers
Content-Type: application/json

{
    "id": 9
}





# Platforms

### Platform add
post http://localhost:3000/api/platforms
Content-Type: application/json

{
    "name": "PC"
}

### Platforms
get http://localhost:3000/api/platforms
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOnsiaWQiOjMsIm5hbWUiOiJOYWd5IFPDoW5kb3IiLCJlbWFpbCI6InNhbmRvckBnbWFpbC5jb20iLCJwZXJtaXNzaW9uIjoxfSwiaWF0IjoxNjQ4NzI0NTcxLCJleHAiOjE2NDg3MjgxNzF9.twd3PxUOjyi8eIoLN_d8hM0BrS_Xmst7pZIBxSflEeQ

### One Platform
get http://localhost:3000/api/platforms/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOnsiaWQiOjMsIm5hbWUiOiJOYWd5IFPDoW5kb3IiLCJlbWFpbCI6InNhbmRvckBnbWFpbC5jb20iLCJwZXJtaXNzaW9uIjoxfSwiaWF0IjoxNjQ4NzI0NTcxLCJleHAiOjE2NDg3MjgxNzF9.twd3PxUOjyi8eIoLN_d8hM0BrS_Xmst7pZIBxSflEeQ

### Platforms edit
put http://localhost:3000/api/platforms
Content-Type: application/json

{
    "name": "PC_updated",
    "id": 1
}

### Delete platform
delete http://localhost:3000/api/platforms
Content-Type: application/json

{
    "id": 5
}





# Games

### Game add
post http://localhost:3000/api/games
Content-Type: application/json

{
    "developerId": 1,
    "gameName": "League of Legends",
    "categoryId": 1,
    "platformId": 1
}

### Games
get http://localhost:3000/api/games
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOnsiaWQiOjMsIm5hbWUiOiJOYWd5IFPDoW5kb3IiLCJlbWFpbCI6InNhbmRvckBnbWFpbC5jb20iLCJwZXJtaXNzaW9uIjoxfSwiaWF0IjoxNjQ4NzI0NTcxLCJleHAiOjE2NDg3MjgxNzF9.twd3PxUOjyi8eIoLN_d8hM0BrS_Xmst7pZIBxSflEeQ

### One game
get http://localhost:3000/api/games/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOnsiaWQiOjMsIm5hbWUiOiJOYWd5IFPDoW5kb3IiLCJlbWFpbCI6InNhbmRvckBnbWFpbC5jb20iLCJwZXJtaXNzaW9uIjoxfSwiaWF0IjoxNjQ4NzI0NTcxLCJleHAiOjE2NDg3MjgxNzF9.twd3PxUOjyi8eIoLN_d8hM0BrS_Xmst7pZIBxSflEeQ

### Game edit
put http://localhost:3000/api/games
Content-Type: application/json

{
    "developerId": 1,
    "gameName": "League of Legends_updated",
    "categoryId": 1,
    "platformId": 1,
    "id": 1
}

### Delete game
delete http://localhost:3000/api/games
Content-Type: application/json

{
    "id": 36
}





# GameLinks

### GameLink add
post http://localhost:3000/api/gamelinks
Content-Type: application/json

{
    "gameId": 1,
    "link": "https://www.youtube.com/watch?v=mDYqT0_9VR4"
}

### Gamelinks
get http://localhost:3000/api/gamelinks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOnsiaWQiOjMsIm5hbWUiOiJOYWd5IFPDoW5kb3IiLCJlbWFpbCI6InNhbmRvckBnbWFpbC5jb20iLCJwZXJtaXNzaW9uIjoxfSwiaWF0IjoxNjQ4NzI0NTcxLCJleHAiOjE2NDg3MjgxNzF9.twd3PxUOjyi8eIoLN_d8hM0BrS_Xmst7pZIBxSflEeQ

### One gamelink
get http://localhost:3000/api/gamelinks/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOnsiaWQiOjMsIm5hbWUiOiJOYWd5IFPDoW5kb3IiLCJlbWFpbCI6InNhbmRvckBnbWFpbC5jb20iLCJwZXJtaXNzaW9uIjoxfSwiaWF0IjoxNjQ4NzI0NTcxLCJleHAiOjE2NDg3MjgxNzF9.twd3PxUOjyi8eIoLN_d8hM0BrS_Xmst7pZIBxSflEeQ

### Gamelink edit
put http://localhost:3000/api/gamelinks
Content-Type: application/json

{
    "gameId": 1,
    "link": "https://www.youtube.com/watch?v=mDYqT0_9VR4 _updated",
    "id": 1
}

### Delete gamelink
delete http://localhost:3000/api/gamelinks
Content-Type: application/json

{
    "id": 57
}