# Login
post http://localhost:3000/api/users/login
Content-Type: application/json

{
    "email": "bernadett1104@gmail.com",
    "password": "admin"
}

### User add
post http://localhost:3000/api/users
Content-Type: application/json

{
    "name": "Sándor Bernadett",
    "email": "bernadett1104@gmail.com",
    "password": "admin",
    "permission": 1
}

### Users
get http://localhost:3000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOnsiaWQiOjMsIm5hbWUiOiJOYWd5IFPDoW5kb3IiLCJlbWFpbCI6InNhbmRvckBnbWFpbC5jb20iLCJwZXJtaXNzaW9uIjoxfSwiaWF0IjoxNjQ4NzI0NTcxLCJleHAiOjE2NDg3MjgxNzF9.twd3PxUOjyi8eIoLN_d8hM0BrS_Xmst7pZIBxSflEeQ

### One User
get http://localhost:3000/api/users/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOnsiaWQiOjMsIm5hbWUiOiJOYWd5IFPDoW5kb3IiLCJlbWFpbCI6InNhbmRvckBnbWFpbC5jb20iLCJwZXJtaXNzaW9uIjoxfSwiaWF0IjoxNjQ4NzI0NTcxLCJleHAiOjE2NDg3MjgxNzF9.twd3PxUOjyi8eIoLN_d8hM0BrS_Xmst7pZIBxSflEeQ

### User edit
put http://localhost:3000/api/users
Content-Type: application/json

{
    "name": "Sándor Bernadett",
    "email": "bernadett1104@gmail.com",
    "password": "admin",
    "permission": 1,
    "id": 4
}

### Delete user
delete http://localhost:3000/api/users
Content-Type: application/json

{
    "id": 4
}





# Categories

### Category add
post http://localhost:3000/api/categories
Content-Type: application/json

{
    "id": 1,
    "name": "multiplayer"
}

### Categories
get http://localhost:3000/api/categories
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOnsiaWQiOjMsIm5hbWUiOiJOYWd5IFPDoW5kb3IiLCJlbWFpbCI6InNhbmRvckBnbWFpbC5jb20iLCJwZXJtaXNzaW9uIjoxfSwiaWF0IjoxNjQ4NzI0NTcxLCJleHAiOjE2NDg3MjgxNzF9.twd3PxUOjyi8eIoLN_d8hM0BrS_Xmst7pZIBxSflEeQ

### One category
get http://localhost:3000/api/categories/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOnsiaWQiOjMsIm5hbWUiOiJOYWd5IFPDoW5kb3IiLCJlbWFpbCI6InNhbmRvckBnbWFpbC5jb20iLCJwZXJtaXNzaW9uIjoxfSwiaWF0IjoxNjQ4NzI0NTcxLCJleHAiOjE2NDg3MjgxNzF9.twd3PxUOjyi8eIoLN_d8hM0BrS_Xmst7pZIBxSflEeQ

### Category edit
put http://localhost:3000/api/categories
Content-Type: application/json

{
    "name": "multiplayer_updated",
    "id": 1
}

### Delete category
delete http://localhost:3000/api/categories
Content-Type: application/json

{
    "id": 1
}





# Developers

### Developer add
post http://localhost:3000/api/developers
Content-Type: application/json

{
    "id": 1,
    "developer": "Riot Games"
}

### Developers
get http://localhost:3000/api/developers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOnsiaWQiOjMsIm5hbWUiOiJOYWd5IFPDoW5kb3IiLCJlbWFpbCI6InNhbmRvckBnbWFpbC5jb20iLCJwZXJtaXNzaW9uIjoxfSwiaWF0IjoxNjQ4NzI0NTcxLCJleHAiOjE2NDg3MjgxNzF9.twd3PxUOjyi8eIoLN_d8hM0BrS_Xmst7pZIBxSflEeQ

### One ceveloper
get http://localhost:3000/api/developers/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOnsiaWQiOjMsIm5hbWUiOiJOYWd5IFPDoW5kb3IiLCJlbWFpbCI6InNhbmRvckBnbWFpbC5jb20iLCJwZXJtaXNzaW9uIjoxfSwiaWF0IjoxNjQ4NzI0NTcxLCJleHAiOjE2NDg3MjgxNzF9.twd3PxUOjyi8eIoLN_d8hM0BrS_Xmst7pZIBxSflEeQ

### Decelopers edit
put http://localhost:3000/api/developers
Content-Type: application/json

{
    "developers": "Riot Games_updated",
    "id": 1
}

### Delete developer
delete http://localhost:3000/api/developers
Content-Type: application/json

{
    "id": 1
}





# Platforms

### Platform add
post http://localhost:3000/api/platforms
Content-Type: application/json

{
    "id": 1,
    "name": "PC"
}

### Platforms
get http://localhost:3000/api/platforms
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOnsiaWQiOjMsIm5hbWUiOiJOYWd5IFPDoW5kb3IiLCJlbWFpbCI6InNhbmRvckBnbWFpbC5jb20iLCJwZXJtaXNzaW9uIjoxfSwiaWF0IjoxNjQ4NzI0NTcxLCJleHAiOjE2NDg3MjgxNzF9.twd3PxUOjyi8eIoLN_d8hM0BrS_Xmst7pZIBxSflEeQ

### One Platform
get http://localhost:3000/api/platforms/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOnsiaWQiOjMsIm5hbWUiOiJOYWd5IFPDoW5kb3IiLCJlbWFpbCI6InNhbmRvckBnbWFpbC5jb20iLCJwZXJtaXNzaW9uIjoxfSwiaWF0IjoxNjQ4NzI0NTcxLCJleHAiOjE2NDg3MjgxNzF9.twd3PxUOjyi8eIoLN_d8hM0BrS_Xmst7pZIBxSflEeQ

### Platforms edit
put http://localhost:3000/api/platforms
Content-Type: application/json

{
    "name": "PC_updated",
    "id": 1
}

### Delete platform
delete http://localhost:3000/api/platforms
Content-Type: application/json

{
    "id": 1
}





# Games

### Game add
post http://localhost:3000/api/games
Content-Type: application/json

{
    "id": 1,
    "developerId": 1,
    "gameName": "League of Legends",
    "categoryId": 1,
    "platformId": 1
}

### Games
get http://localhost:3000/api/games
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOnsiaWQiOjMsIm5hbWUiOiJOYWd5IFPDoW5kb3IiLCJlbWFpbCI6InNhbmRvckBnbWFpbC5jb20iLCJwZXJtaXNzaW9uIjoxfSwiaWF0IjoxNjQ4NzI0NTcxLCJleHAiOjE2NDg3MjgxNzF9.twd3PxUOjyi8eIoLN_d8hM0BrS_Xmst7pZIBxSflEeQ

### One game
get http://localhost:3000/api/games/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOnsiaWQiOjMsIm5hbWUiOiJOYWd5IFPDoW5kb3IiLCJlbWFpbCI6InNhbmRvckBnbWFpbC5jb20iLCJwZXJtaXNzaW9uIjoxfSwiaWF0IjoxNjQ4NzI0NTcxLCJleHAiOjE2NDg3MjgxNzF9.twd3PxUOjyi8eIoLN_d8hM0BrS_Xmst7pZIBxSflEeQ

### Game edit
put http://localhost:3000/api/games
Content-Type: application/json

{
    "developerId": 1,
    "gameName": "League of Legends_updated",
    "categoryId": 1,
    "platformId": 1,
    "id": 1
}

### Delete game
delete http://localhost:3000/api/games
Content-Type: application/json

{
    "id": 1
}